config/routes.rb
Pleduc::Application.routes.draw do

  	# devise alumnos
  	devise_for :alumnos, :controllers => {:registrations => "alumnos/registrations"} 
	
	# devise profesores
  	devise_for :profesors, :controllers => {:registrations => "profesors/registrations"}
  	
  	# devise apoderados
  	devise_for :apoderados, :controllers => {:registrations => "apoderados/registrations"} 
	
  	# default route
  	root 'home#index'
  	# comenzar
  	get '/comenzar' => 'home#comenzar', as: 'comenzar'

  	# ======================================================================================== 	
  	# rutas profesores
  	# ========================================================================================
  	get '/profesores' => "profesors/home#index", as: 'home_profesor'
  	get '/profesores/update' => 'profesors/update#info', as: 'update_info_profesor'
  	patch '/profesores/update' => 'profesors/update#update', as: 'update_info_form_profesor'

    # cursos profesor
    get '/profesores/cursos' => 'profesors/cursos#index', as: 'cursos_profesor'
    get '/profesores/cursos/:id/edit' => 'profesors/cursos#edit', as: 'edit_cursos_profesor'
    get '/profesores/cursos/:id/alumnos' => 'profesors/cursos#alumnos', as: 'alumnos_cursos_profesor'
    post '/profesores/cursos/:id/alumnos/nuevo' => 'profesors/cursos#add', as: 'add_alumnos_cursos_profesor'
    get '/profesores/cursos/:curso_id/alumno/:alumno_id/delete' => 'profesors/cursos#delete_alumno', as: 'del_alumnos_cursos_profesor'

    get '/profesores/cursos/nuevo' => 'profesors/cursos#new', as: 'create_cursos_profesor'
    post '/profesors/cursos/create' => 'profesors/cursos#create', as: 'post_cursos_profesor'
    patch '/profesors/cursos/update' => 'profesors/cursos#update', as: 'update_cursos_profesor'
    get '/profesors/cursos/:id/destroy' => 'profesors/cursos#destroy', as: 'destroy_cursos_profesor'

  	# ========================================================================================
  	# rutas apoderados
  	# ========================================================================================
  	get '/apoderados' => 'apoderados/home#index', as: 'home_apoderado'
  	get '/apoderados/update' => 'apoderados/update#info', as: 'update_info_apoderado'
  	patch '/apoderados/update' => 'apoderados/update#update', as: 'update_info_form_apoderado'

  	# ========================================================================================
  	# rutas alumnos
  	# ========================================================================================
  	get '/alumnos' => 'alumnos/home#index', as: 'home_alumnos'
  	get '/alumnos/update' => 'alumnos/update#info', as: 'update_info_alumno'
  	patch '/alumnos/update' => 'alumnos/update#update', as: 'update_info_form_alumno'

    # ========================================================================================
    # rutas cursos
    # ========================================================================================

    get '/curso/:id' => 'cursos/cursos#index', as: 'curso'
    
    get '/curso/:id/descripcion' => 'cursos/cursos#desc', as: 'desc_curso'
    patch '/curso/descripcion' => 'cursos/cursos#update', as: 'desc_update_curso'

    get '/curso/:id/noticias/nueva' => 'cursos/noticias#new', as: 'nueva_noticia_curso'
    post '/curso/noticias/' => 'cursos/noticias#create', as: 'post_noticia_curso'

    post '/curso/:id/uploads' => 'cursos/cursos#upload', as: 'curso_upload'
    get '/curso/delete/:file' => 'cursos/cursos#delete', as: 'curso_delete'
end

app/models/curso.rb
class Curso < ActiveRecord::Base
	belongs_to :profesor

	has_many :alumnos
	has_many :noticias
  has_many :uploads
end

app/controllers/cursos/cursos_controller.rb
class Cursos::CursosController < ApplicationController
  before_action :set_curso, only: [:index]
  layout 'layout'
  # GET /cursos
  def index
  	@noticias = Noticias.all.where(curso_id: @curso.id).order('created_at DESC')
  end

  def desc
  	@curso = Curso.find(params[:id])
  end

  def update
  	@curso = Curso.find(params[:curso][:curso_id])
  	if @curso.update(curso_params)
  		redirect_to curso_path(@curso), notice: 'Descripcion actualizada'
  	end
  end

  def upload
    @file = Upload.new(upload_params)
    @file.curso_id = params[:id]
    if @file.save
      redirect_to curso_path(@file.curso_id), notice: 'Material subido exitosamente.'
    else
      redirect_to curso_path(@file.curso_id), notice: 'Material subido exitosamente.'
    end
  end

  private
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:desc)
    end

    def upload_params
      params.require(:upload).permit(:titulo, :file)
    end
end

app/controllers/cursos/noticias_controller.rb
class Cursos::NoticiasController < ApplicationController
  layout 'layout'

  def new
    @curso = Curso.find(params[:id])
  end


  def create
    @noticia = Noticias.new(noticias_params)
    if @noticia.save
      redirect_to curso_path(@noticia.curso_id), notice: 'Noticia agregada'
    else
      redirect_to curso_path(@noticia.curso_id), alert: 'No se puduo agregar la noticia'
    end
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def noticias_params
      params.require(:noticias).permit(:titulo, :contenido, :curso_id)
    end

end

app/controllers/profesors/cursos_controller.rb
class Profesors::CursosController <  ActionController::Base
    before_filter :authenticate_profesor!
    before_filter :set_curso, only: [:update]
    # home controller apoderados
    layout 'layout'
  
	def index
		@cursos = Curso.all
	end

	def edit
		@curso = Curso.find(params[:id])
	end

	def alumnos
		@curso = Curso.find(params[:id])
		@alumnos = @curso.alumnos
	end

	def add
		
		if Alumno.where(rut: params[:alumno][:rut]).exists?
			@alumno = Alumno.where(rut: params[:alumno][:rut]).first
			@alumno.curso_id = params[:alumno][:curso_id]
			if @alumno.save
				redirect_to alumnos_cursos_profesor_path(params[:alumno][:curso_id]), notice: "Alumno agregado."
			end
		else
			redirect_to alumnos_cursos_profesor_path(params[:alumno][:curso_id]), alert: "Alumno no existe, no se pudo agregar."
		end
	end


	def delete_alumno
		@alumno = Alumno.find(params[:alumno_id])
		@alumno.curso_id = nil
		if @alumno.save
			redirect_to alumnos_cursos_profesor_path(params[:curso_id]), notice: 'Alumno eliminado del curso'
		else
			redirect_to alumnos_cursos_profesor_path(params[:curso_id]), alert: 'Alumno no ha sido eliminado del curso'
		end
	end

	# GET /cursos/new
  def new
    @curso = Curso.new
  end

  # POST /cursos
  def create
    @curso = Curso.new(curso_params)

    if @curso.save
      redirect_to cursos_profesor_path, notice: 'Curso agregado.'
    else
      render :new
    end
  end

  # PATCH/PUT /cursos/1
  def update
    if @curso.update(curso_params)
      redirect_to cursos_profesor_path, notice: 'Curso se ha actualizado.'
    else
      render :edit
    end
  end

  # DELETE /cursos/1
  def destroy
  	@curso = Curso.find(params[:id])
    @curso.destroy
    redirect_to cursos_profesor_path, notice: 'Curso eliminado.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:curso][:curso_id])
    end

    # Only allow a trusted parameter "white list" through.
    def curso_params
      params.require(:curso).permit(:nombre, :sigla, :profesor_id)
    end

	# Use callbacks to share common setup or constraints between actions.
	def set_alumno
	  @alumno = current_alumno
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def alumno_params
	  params.require(:alumno).permit(:nombres, :apellidos, :fecha_de_nacimiento, :nivel, :curso, :email, :password, :password_confirmation)
	end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/cursos/desc.html.erb
<div class="top-info">
  <h2>Descripción Curso</h2><span class="desc"><%= @curso.nombre %></span>
</div>


<div class="mid-info">
  <%= form_for @curso, url: desc_update_curso_path do |f| %>


<div class="form-group">
    <label for="inputEmail3" class="col-sm-3 control-label">Descripción</label>
    <div class="col-sm-9">
    	<%= f.text_area :desc, :class => 'form-control' %>
    </div>
</div>

	<%= f.hidden_field :curso_id, value: @curso.id %>

  <%= f.submit "Agregar", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/cursos/cursos/index.html.erb
<div class="top-info">
  <h2>Curso <%= @curso.nombre %></h2><span class="desc"><%= @curso.sigla %></span>
</div>


<div class="mid-info">
	<div class="noticia">
		<% if not @curso.desc.blank? %>
  			<p><%= @curso.desc %></p>
  		<% else %>
  			No hay una descripción del curso. 
  		<% end %>
  	</div>

  <% if profesor_signed_in? %>
  <div class="text-right">
  	<%= link_to "Editar descripción", desc_curso_path(@curso.id), class: 'btn btn-xs btn-primary' %>
  </div>
  	<% end %>
</div>


<div class="top-info">
  <h2>Últimas Noticias</h2><span class="desc"><%= @curso.sigla %></span>

</div>


<div class="mid-info">
  
  <% if @noticias.count > 0 %>
  	<% @noticias.each do |n| %>

  	<div class="noticia">
  		<h5><%= n.titulo %></h5>
  		<p><%= raw n.contenido %></p>
  		<p class="publised_at">Publicado en: <%= n.created_at %></p>
  	</div>

  	<% end %>

  <% else %>
  	<p>No se registran noticias.
  <% end %>
  <br />
  <% if profesor_signed_in? %>
  <div class="text-right">
  	<%= link_to "Agregar noticia", nueva_noticia_curso_path(@curso.id), class: 'btn btn-xs btn-primary' %>
  </div>
  <% end %>
</div>

<div class="top-info">
  <h2>Material</h2><span class="desc"><%= @curso.sigla %></span>
</div>


<div class="mid-info">
  <h4>Material disponible</h4>

  <table class="table">
    <thead>
      <tr>
        <th>Título Material</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @curso.uploads.each do |u| %>
      <tr>
        <td><h6><%= u.titulo %></h6></td>
        <td>
          <%= link_to "Descargar", u.file.url(:original, false), class: 'btn btn-xs btn-primary' %>
          <%= link_to "Eliminar", curso_delete_path(u.id), class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

<% if profesor_signed_in? %>
<h4>Subir Material</h4>

<%= form_for(Upload.new, :url => curso_upload_path(@curso.id), :html => {:class => 'form-horizontal'}) do |f| %>

<div class="form-group">
    <label for="inputEmail3" class="col-sm-3 control-label">Título</label>
    <div class="col-sm-9">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
</div>

 <div class="form-group">
    <label for="inputEmail3" class="col-sm-3 control-label">Seleccionar Archivo</label>
    <div class="col-sm-9">
      <%= f.file_field :file, :class => 'form-control' %>
    </div>
</div>
  
<div class="text-right">
  <%= f.submit "Subir Material", class: 'btn btn-primary btn-xs' %>
</div>
  <% end %>
<% end %>
</div>


<div class="top-info">
  <h2>Videos</h2><span class="desc"><%= @curso.sigla %></span>
</div>


<div class="mid-info">
  <p>videos</p>
</div>



<div class="top-info">
  <h2>Links de interés</h2><span class="desc"><%= @curso.sigla %></span>
</div>


<div class="mid-info">
  <p>links</p>
</div>